### ISSUE TITLE
（v0.8.1）Errors occured with same steps in v0.8.0.

### ISSUE THREAD

**Issue by zoelir729** [kschan0214/sepia#14]
Sorry to bother!
I have met a problem in using v0.8.1.
Picture 1 showed the steps I chose in v0.8.0, processing pipeline could completed, and I chose the same options in v0.8.1, but errors occured (picture 2).

![image](https://user-images.githubusercontent.com/36666968/114883154-3a186800-9e37-11eb-8d0a-812824a8f7f5.png)

![image](https://user-images.githubusercontent.com/36666968/114882069-28829080-9e36-11eb-80ec-52d7d06ca62b.png)

**Comment by kschan0214** [comment]
Hi Zoe, the error comes from the mismatch between the length of the echo times (TE) and the time dimension (4th) of the magnitude data. These two pieces of information have to be consistent for a few steps required in SEPIA QSM processing. Can you check if the number of the elements in the parameter 'TE' in the sepia_head.mat file have the same number of time series images in the magnitude and phase data and report back?

**Comment by zoelir729** [comment]
I checked the data, the number of the elements in the parameter 'TE' in the sepia_head.mat file (TE=0.0236) indeed did not have the same number of time series images in the magnitude and phase data (both TE=24).
How to deal with this issue?
![image](https://user-images.githubusercontent.com/36666968/115866480-4cfcef00-a46c-11eb-9d06-7aea488d374a.png)
![image](https://user-images.githubusercontent.com/36666968/115866497-525a3980-a46c-11eb-9c41-20d295625740.png)

**Comment by kschan0214** [comment]
The most straightforward way is to modify the sepia_header.mat file by manually overwriting all the echo times (in second): e.g. in the Matlab command window:
```
clear all;
load('sepia_header.mat');
TE = [TE1,TE2,TE3,....,TE24]; % where TE1, TE2, TE3... are the echo times of each echo in the unit of second
delta_TE = TE2 - TE1;
save('sepia_header.mat');
```

Alternatively, if you have the JSON file(s) that contains all echo time information of the data (available if using dcm2niix or dicm2nii DICOM to NIFTI conversion tools), you can use these file as the input in the 'Get header info' function. The SEPIA should be able to read all the echo times in the files.  

![Screenshot 2021-04-23 at 14 14 23](https://user-images.githubusercontent.com/39571502/115869722-96364a00-a43e-11eb-8c9b-79499d1ffaa9.png)

Let please me know if this works for you.

**Comment by zoelir729** [comment]
Actually, the sepia_header.mat file I used was obtained using 'Get header info' function of the SEPIA.
The processing pipeline did not work successfully in v 8.0.1 but well in v 0.8.0.

**Comment by kschan0214** [comment]
In v0.8.1 we added several procedures to make sure the input data (header and images) are consistent. The issue you encountered is one of those, which indicates there are some TE information missing in the header.

If you already used the 'Get header info' function, it is likely the JSON file does not contain all the echo times of the acquisition. This can be checked by looking up the 'EchoTime' or 'EchoTimes' tag in the file. If there is only 1 value instead of all the echoes, then the TE information is not complete. This could happen if you use dcm2niix to convert the data from DICOM to NIFTI format with the 'merge' option as 'yes' (more explanation here: https://sepia-documentation.readthedocs.io/en/latest/getting_started/Data-preparation.html). On the other hand, if you have separate JSON files for each echo, you will then need to select **all** JSON files when selecting the TE files.

If the JSON file(s) doesn't have the complete TE information, you can manually overwrite it in the GUI, e.g.:
![Screenshot 2021-04-24 at 10 57 03](https://user-images.githubusercontent.com/39571502/115953487-18307c80-a4ec-11eb-9fc0-fffd99b8f329.png)

**Comment by kschan0214** [comment]
Hi Zoe, 

I would like to follow up your issue. Is it being solved? 

If not, would you mind clarifying that whether you are running on multi-echo data or single echo data? It seems that you are running on a single-echo dataset based on the header but I might misunderstand that you are running on a multi-echo dataset. If you are working on single echo data, can you update SEPIA to the current 'master' branch and test on your dataset again?

Best,

Kwok

**Comment by zoelir729** [comment]
Sorry to reply for a long time!
Indeed the data I used was single echo data.
Now I have updated SEPIA to the current v 0.8.1.1.
However, another error occurred.
![image](https://user-images.githubusercontent.com/36666968/123970010-56b24e00-d9eb-11eb-8c95-04442ff213f3.png)
And the version sepia-0.8.0 could still work without errors reports.
Hope you can offer some suggestions.
Thanks!

Best,
Zoe

**Comment by zoelir729** [comment]
The error had been fixed. (some unexpected mismatched metadata was found finally.)
Thank you for your reply and recommendation. 
And at present, another issue puzzled me. 
I will open a new issue.  Hope you can give me some instructions.
