### ISSUE TITLE
error while running sepia

### ISSUE THREAD

**Issue by miladseyfi** [kschan0214/sepia#5]
Hello dear 
This is the error occurred while trying to run sepia.m : 

Undefined function or variable 'SEGUE_dir'.
Error in sepia_addpath (line 15)
CheckPathValidity(MEDI_dir,STISuite_dir,FANSI_dir,SEGUE_dir);
Error in sepia (line 48)
sepia_addpath; 

what is this direction for  ? I read the documentation but this directory was not mentioned . 
I hope you could help me 
thanks a lot!

**Comment by kschan0214** [comment]
Hi,

Thanks for reporting this! The master branch supports a new phase unwrapping algorithm called [SEGUE](https://www.ncbi.nlm.nih.gov/pubmed/30561341). If you want to include it in the SEPIA framework, you can download it [here](https://xip.uclb.com/i/software/SEGUE.html), and specify the 'SEGUE_dir', which is the path to the folder containing the SEGUE functions, in the SpecifyToolboxesDirectory.m likes other toolboxes. 

I haven't built a fail-safe script for people who don't have SEGUE yet but it will be fixed in the next stable release. For a quick solution of the problem, you can add the following line to the end of the SpecifyToolboxesDirectory.m script:
SEGUE_dir = [];
In this way, SEPIA will give a warning message about missing SEGUE directory but other than that SEPIA should work fine. 

Let me know if this works for you or not.

Kwok

**Comment by kschan0214** [comment]
Since there is no more update, I will close this issue.
