### ISSUE TITLE
Problems in Phase unwrapping using ROMEO

### ISSUE THREAD

**Issue by Shashank-Vijayaprasadh** [kschan0214/sepia#85]
Hii I have been working on SEPIA toolbox for a while and I have run into some problems with the scans using the ROMEO. The scans look messy starting from the field map stage till end of SEPIA processing pipeline and I have little clue on what could have gone wrong. It would be great if you can take a look into it! I use SEPIA 1.2.2.3 for processing. I will add the images of the chimap and fieldmap of good and bad brain scans.

<img width="731" alt="Chimap bad" src="https://github.com/kschan0214/sepia/assets/161452692/951f1455-ecb2-4752-8565-0c71e0c3e0e9">
<img width="731" alt="Fieldmap bad" src="https://github.com/kschan0214/sepia/assets/161452692/a45795d5-1f74-4884-be78-aa23402ec5ff">
<img width="739" alt="Chimap good" src="https://github.com/kschan0214/sepia/assets/161452692/3a1d740d-b024-4498-9c9b-45b83062e160">
<img width="849" alt="Fieldmap good" src="https://github.com/kschan0214/sepia/assets/161452692/c4813b59-4734-485e-b374-74d66a001ae4">

**Comment by kschan0214** [comment]
Hi Shashank,

Thanks for getting in touch. I failed to re-create the issue in my first attempt using SEPIA v1.2.2.3. Can you provide the following information to me so that I can re-create the issue under the same circumstances:

- Matlab version
- OS version
- ROMEO version
- a copy of the sepia_config.m file

Thanks!

**Comment by kschan0214** [comment]
Hi Shashank,

Thanks for the information. I managed to reproduce the same issue as you encountered. The issue occurred when both the bipolar eddy current phase correction and the MCPC-3D-S phase offset removal of ROMEO were set 'on'. I am not sure why exactly this happens on some dataset when the others are unaffected, as the bipolar eddy current corrected data does not contain any unusual value (e.g. NaN, inf, etc.) when I checked but I guess it could be due to some voxels that have very low SNR created a sharp change in phase after the correction which might cause the error in MCPC-3D-S processing later on. 

The phase unwrapping and echo combination step works without error when only either one of the correction is enabled (i.e. bipolar eddy correction -> 'on' and MCPC-3D-S -> 'off'; or bipolar eddy correction -> 'off' and MCPC-3D-S -> 'on').  Based on my observation on your data, it seems to me that the data was acquired using monopolar gradient readout. If this is the case, you should turn off the bipolar eddy correction to avoid over-correcting the data, i.e.:
`algorParam.unwrap.isEddyCorrect = 0;`

Let me know if this solve your problem!

**Comment by Shashank-Vijayaprasadh** [comment]
Dear Kwok,
Sorry for the late reply. Indeed after turning off the bipolar eddy correction, the algorithm worked! Thank you
